spring:
  # 配置mysql数据库，springbootdemodat为我的数据库名称
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdat?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: mwt.0809
    driver-class-name: com.mysql.cj.jdbc.Driver


# spring集成Mybatis环境
# 加载Mybatis映射文件
mybatis:
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8088